### ISSUE TITLE
on clicking the cancel button loader showing in save button

### ISSUE THREAD

**Issue by harshmangalam** [x-ploration-of-mars/x-stack#1]
In `https://x-stack.vercel.app/settings/profile/` Profile route when i  click the cancel button the loader showing for save button.

**Comment by maiieul** [comment]
Thanks for the issue! I was going to try and fix it, but I agree with https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/reset that cancel buttons can lead to poor UX. Going to remove it.
